### ISSUE TITLE
Create resource definition

### ISSUE THREAD

**Issue by NilsPonsard** [do3-2021/kudo#14]
### What is the problem you're trying to solve?

We need to establish a flexible and extensible schema to define workloads and other data types like users.

### Task list

- [ ] Define base schema
- [ ] Workload schema

**Comment by MathieuSoysal** [comment]
The first proposal of [Workload definition](https://github.com/do3-2021/kudo/commit/fd1322828b3b6c8d7e0625d25e197302b08b9c8c?short_path=12ca06e#diff-12ca06e32bc843fcde95ebb89297e36c3aa525fa5de486c7b5134f0a5e2012c7) :

```json

Workload : {
    name : ""
    type : 
    executable : // maybe change the name
    ressouces : {
        cpu : 
        ram : 
        disk :
    }
    port : 
}
```

**Comment by MathieuSoysal** [comment]
The first proposal of [Workload definition](https://github.com/do3-2021/kudo/commit/fd1322828b3b6c8d7e0625d25e197302b08b9c8c?short_path=12ca06e#diff-12ca06e32bc843fcde95ebb89297e36c3aa525fa5de486c7b5134f0a5e2012c7) by @NilsPonsard  :

```json
{
    "Workload" : {
        "name" : "",
        "type" : "",
        "executable" : "", // maybe change the name
        "ressources" : {
            "cpu" : "",
            "ram" : "",
            "disk" : "",
        },
        "port" : "" 
    }
}
```
